name: build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  ARTIFACT_PATH: ${{ github.workspace }}/artifact
  BUILD_PATH: ${{ github.workspace }}/build
  PACKAGE_PATH: ${{ github.workspace }}/package
  SOURCE_PATH: ${{ github.workspace }}/code

jobs:
  build-openvino-plugins-x86_64:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}

      - name: Download Audacity
        uses: robinraju/release-downloader@v1
        with:
          repository: 'audacity/audacity'
          out-file-path: ${{ env.SOURCE_PATH }}
          latest: true
          tarBall: true
          extract: true
      
      - name: Download Whisper.cpp
        uses: robinraju/release-downloader@v1
        with:
          repository: 'ggml-org/whisper.cpp'
          out-file-path: ${{ env.SOURCE_PATH }}
          latest: true
          tarBall: true
          extract: true
      
      - name: Build audacity for x86_64
        run: |
          .github/scripts/build-x86_64.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-openvino-x86_64
          path: mod-openvino-x86_64/

  build-openvino-plugins-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}

      - name: Download Audacity
        uses: robinraju/release-downloader@v1
        with:
          repository: 'audacity/audacity'
          out-file-path: ${{ env.SOURCE_PATH }}
          latest: true
          tarBall: true
          extract: true
      
      - name: Download Whisper.cpp
        uses: robinraju/release-downloader@v1
        with:
          repository: 'ggml-org/whisper.cpp'
          out-file-path: ${{ env.SOURCE_PATH }}
          latest: true
          tarBall: true
          extract: true
      
      - name: Build audacity for arm64
        run: |
          .github/scripts/build-arm64.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-openvino-arm64
          path: mod-openvino-arm64/
        

      # - name: Pack Audacity.app
      #   run: |
      #     .github/scripts/pack.sh

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.PACKAGE_NAME }}
      #     path: ${{ env.ARTIFACT_PATH }}/${{ env.PACKAGE_NAME }}.zip
      #     retention-days: 89
