name: build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  ARTIFACT_PATH: ${{ github.workspace }}/artifact
  BUILD_PATH: ${{ github.workspace }}/build
  PACKAGE_PATH: ${{ github.workspace }}/package
  SOURCE_PATH: ${{ github.workspace }}/code

jobs:
  build-openvino-plugins:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}

      - name: Download Audacity
        uses: robinraju/release-downloader@v1
        with:
          repository: 'audacity/audacity'
          out-file-path: ${{ env.SOURCE_PATH }}
          latest: true
          tarBall: true
          extract: true
      
      - name: Download Whisper.cpp
        uses: robinraju/release-downloader@v1
        with:
          repository: 'ggml-org/whisper.cpp'
          out-file-path: ${{ env.SOURCE_PATH }}
          latest: true
          tarBall: true
          extract: true
      
      - name: Build audacity
        run: |
          .github/scripts/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-openvino-arm
          path: mod-openvino-arm/
        

      # - name: Pack Audacity.app
      #   run: |
      #     .github/scripts/pack.sh

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.PACKAGE_NAME }}
      #     path: ${{ env.ARTIFACT_PATH }}/${{ env.PACKAGE_NAME }}.zip
      #     retention-days: 89
